In [1]:
# Objective: Real-World aspect: To develop a program to  recognize the hand written digit
            #Computer Science: Multi-Class Classification Task (Problem)

In [1]:
from keras import models
from keras import layers
from keras.datasets import mnist

In [3]:
# 2. Data Acquisition (Data Collection)

In [2]:
(train_images, train_labels), (test_images, test_labels)  = mnist.load_data()

In [9]:
train_images.shape

(60000, 28, 28)

In [10]:
test_images.shape

(10000, 28, 28)

In [4]:
len(train_labels)

60000

In [5]:
len(test_labels)

10000

In [7]:
# 3. Data Preprocessing - ID for DNN; type case float - Scaling

x_train = train_images.reshape((60000,28*28))
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [8]:
x_train.shape

(60000, 784)

In [9]:
x_test = test_images.reshape((10000,28*28))

In [10]:
x_test.shape

(10000, 784)

In [11]:
x_train[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [12]:
x_train = x_train.astype('float32') / 255

In [13]:
x_train[0] 

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [14]:
x_test = x_test.astype('float32') / 255

In [15]:
from keras.utils import to_categorical

y_train = to_categorical(train_labels)
y_test = to_categorical(test_labels)

In [16]:
# 5. Modeling - a: Build up the architecture of the DNN

model  = models.Sequential()
model.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
model.add(layers.Dense(10, activation='softmax'))

c:\Users\Shiraz Mazhar\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [17]:
# 5. Modeling - b: Compile the model of the DNN 
model.compile(
                optimizer='rmsprop',
                loss = 'categorical_crossentropy',
                metrics = ['acc']
                  
             )

In [18]:
# 5. Modeling - c: Learning or Training  the DNN model 

model.fit(x_train,
          y_train,
          epochs=5,
          batch_size = 128
         )

Epoch 1/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - acc: 0.8775 - loss: 0.4342
Epoch 2/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - acc: 0.9665 - loss: 0.1173
Epoch 3/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - acc: 0.9789 - loss: 0.0725
Epoch 4/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - acc: 0.9847 - loss: 0.0517
Epoch 5/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - acc: 0.9885 - loss: 0.0373


In [19]:
# 6. Model Evaluation 

t_loss, t_acc = model.evaluate(x_test, y_test)
print(f'Test Accuracy of the Model:{t_acc}')

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - acc: 0.9775 - loss: 0.0764
Test Accuracy of the Model:0.9810000061988831


In [20]:
model.save('HandWrittenDigitModel.h5')